name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build and List Files
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug
        echo "=== FILE STRUCTURE ==="
        find . -name "*.apk" -type f
        echo "=== BUILD OUTPUTS ==="
        ls -la app/build/outputs/
      
    - name: Upload ANY APK Found
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: "**/*.apk"
