name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download correct gradle-wrapper.jar
      run: |
        wget -O gradle/wrapper/gradle-wrapper.jar https://repo.maven.apache.org/maven2/gradle/wrapper/gradle-wrapper/8.5/gradle-wrapper-8.5.jar
        chmod +x ./gradlew
        
    - name: Build APK
      run: ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app
        path: app/build/outputs/apk/**/*.apk
